Yet more setup script debugging

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -218,21 +218,21 @@ case $1 in
 		# Supervisord
 		###############################################
 
-
-		if ! diff -u conf/supervisord/appserver.conf /etc/supervisor/conf.d/BeerCrush-app.conf > /dev/null; then
-			echo "**************************************************";
-			echo "ERROR: Supervisor config (/etc/supervisor/conf.d/BeerCrush-app.conf) is incorrect:";
-			echo "**************************************************";
-			diff -u conf/supervisord/appserver.conf /etc/supervisor/conf.d/BeerCrush-app.conf;
-			exit;
-		fi
-
 		# Verify that supervisord is config'd
 		if [ ! -f /etc/supervisor/conf.d/BeerCrush-app.conf ]; then
 			echo "I don't see /etc/supervisor/conf.d/BeerCrush-app.conf. You can get one from svn://beercrush/conf/supervisord/appserver.conf."
 			exit;
 		fi
 		
+		MYIP=`/sbin/ifconfig eth0 |grep "inet addr:" | sed -e 's/inet addr://' |  awk '{print $1}'`;
+		if ! sed -e "s/MYIPADDRESS/$MYIP/" conf/supervisord/appserver.conf | diff -u - /etc/supervisor/conf.d/BeerCrush-app.conf > /dev/null; then
+			echo "**************************************************";
+			echo "ERROR: Supervisor config (/etc/supervisor/conf.d/BeerCrush-app.conf) is incorrect:";
+			echo "**************************************************";
+			sed -e "s/MYIPADDRESS/$MYIP/" conf/supervisord/appserver.conf | diff -u - /etc/supervisor/conf.d/BeerCrush-app.conf;
+			exit;
+		fi
+
 		# Verify that /var/run/supervisor exists
 		if [ ! -d /var/run/supervisor ]; then
 			echo "Creating /var/run/supervisor";
