A bunch of minor changes from TODO list:  * 0807f71 removed unnecessary TODO    * setup  * f4e1c9d logs Spread failures    * php/include/OAK/jobs.class.php    * php/include/OAK/listener.class.php  * 04619e8 removed TODO    * api/place/photo.php  * e5f4afc validates styles against real styles list    * api/beer/edit.php  * 66a0534 added log message    * daemons/uncache/uncache  * 7b4669e validate function can set converted value now    * php/include/OAK/oak.class.php  * 33b22ef set exact value of miles per  1 degree of latitude    * api/location/nearby_locations.cc    * src/nearby_beer.cc  * 6a77fcb removed a TODO    * setup  * 72eecb6 verifies that menu_id is a menu ID and that beer IDs are legit    * api/menu/edit.php  * 17c8548 commented login, no longer necessary    * api/menu/test/addbeer  * 3c677ad added is_a_menu()    * php/include/beercrush.php  * b99756d better message for invalid JSON input    * tools/jsontidy  * 14d2d39 uses API for beer reviews rather than going straight to db    * api/review/beer.php  * 84a0ee0 uses API to get reviews rather than going straight to the db    * api/review/place.php  * 4253b48 validates user_id on reviews    * api/beer/review.php  * 516f762 added TODO    * api/photo/newphoto  * 781f41f removed TODO comment    * api/beer/photo.php    * api/brewery/photo.php  * 62a3730 uses the file's time to determine whether to load the file again    * api/autocomplete/autocomplete.cc

diff --git a/api/menu/test/addbeer b/api/menu/test/addbeer
--- a/api/menu/test/addbeer
+++ b/api/menu/test/addbeer
@@ -78,14 +78,14 @@ if [ -z "$serving_type" ]; then
 fi
 
 
-response=$(curl --silent --fail -d email=$email -d password=$password $api_url/login);
-if [ $? -ne 0 ]; then
-	echo "Failed to login";
-	exit;
-fi
-
-userid=$(echo $response | $bindir/jsonpath -1 userid);
-usrkey=$(echo $response | $bindir/jsonpath -1 usrkey);
+# response=$(curl --silent --fail -d email=$email -d password=$password $api_url/login);
+# if [ $? -ne 0 ]; then
+# 	echo "Failed to login";
+# 	exit;
+# fi
+# 
+# userid=$(echo $response | $bindir/jsonpath -1 userid);
+# usrkey=$(echo $response | $bindir/jsonpath -1 usrkey);
 
 add_item="$beer_id;$serving_type";
 
