gets beer reviews too

diff --git a/api/test/apitest b/api/test/apitest
--- a/api/test/apitest
+++ b/api/test/apitest
@@ -92,6 +92,7 @@ while read brewery_id; do
 done < <(brewery_list);
 
 echo "Getting $total_breweries brewery docs...";
+http_request_reset;
 while read brewery_id; do
 	# echo $brewery_id;
 	brewery_url=$base_uri/${brewery_id//:/\/}
@@ -99,9 +100,11 @@ while read brewery_id; do
 		echo "ERROR: $brewery_url";
 	fi
 done < <(brewery_list);
+http_request_summary;
 
 echo "Getting $total_breweries beerlist docs...";
 total_beerlist_beers=0;
+http_request_reset;
 while read brewery_id; do
 	beerlist_url=$base_uri/${brewery_id//:/\/}/beerlist
 	# echo $beerlist_url;
@@ -121,6 +124,7 @@ while read brewery_id; do
 		# done
 	fi
 done < <(brewery_list);
+http_request_summary;
 
 total_beers=0;
 while read beer_id; do
@@ -128,17 +132,30 @@ while read beer_id; do
 done < <(beer_list);
 
 echo "Getting $total_beers beer docs...";
+http_request_reset;
 while read beer_id; do
 	beer_url=$base_uri/${beer_id//:/\/};
 	if ! http_request $beer_url > /dev/null; then
 		echo "ERROR: $beer_url";
 	fi
 done < <(beer_list);
+http_request_summary;
+
+#
+# Get reviews for each beer
+#
+echo "Getting $total_beers review docs...";
+http_request_reset;
+while read beer_id; do
+	reviews_url=$base_uri/review/${beer_id//:/\/}/0;
+	if ! http_request $reviews_url > /dev/null; then
+		echo "ERROR: $reviews_url";
+	fi
+done < <(beer_list);
+http_request_summary;
 
 echo;
 echo "$total_breweries breweries";
 echo "$total_beers beers";
 echo "$total_beerlist_beers beers listed on brewery beer lists";
 echo;
-
-http_request_summary;
