Improving make system

diff --git a/tools/iamservertype b/tools/iamservertype
--- a/tools/iamservertype
+++ b/tools/iamservertype
@@ -1,26 +1,56 @@
 #!/bin/bash
 
+QUIET=0;
+ISTYPE=0;
+
+while getopts "q" opt; do
+	case $opt in 
+		q)
+			QUIET=1;
+			shift;
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			;;
+	esac
+done
+
 # Get my IP(s)
 MYIPS=$(/sbin/ifconfig |grep "inet addr:" | sed -e 's/ *inet  *addr:\([0-9\.]*\).*$/\1/');
 
 SERVER_TYPE_IPS=$(cat /etc/BeerCrush/setup.conf | php -r '
 $conf=json_decode(stream_get_contents(STDIN));
-foreach ($conf->servers->{$argv[1]}->servers as $s) {
-	list($ip,$port)=preg_split("/:/",$s);
-	print $ip;
-}; 
+if (!is_null($conf)) {
+	foreach ($conf->servers->{$argv[1]}->servers as $s) {
+		list($ip,$port)=preg_split("/:/",$s);
+		print "$ip ";
+	}
+}
 ' $1);
 
 for S in $SERVER_TYPE_IPS; do
 	S=`dig $S +short`;
 	for MY in $MYIPS; do
-		if [ "$S" == "$MY" ]; then
-			echo "Yes";
-			exit 0;
+		if [ "$S" = "$MY" ]; then
+			let ISTYPE=1;
 		fi
 	done
 done
 
-echo "No";
-exit 1;
+if [ $ISTYPE = 1 ]; then
+
+	if [ $QUIET = 0 ]; then 
+		echo "Yes"; 
+	fi
+
+	exit 0;
+	
+else
+
+	if [ $QUIET = 0 ]; then
+		echo "No"; 
+	fi
+
+	exit 1;
+fi
 
